volumes:
  registry:
  registry_config:

services:
  config:
    build:
      context: config
    restart: "no"
    environment:
      - REGISTRY_STORAGE_BACKEND=${REGISTRY_STORAGE_BACKEND}
      - REGISTRY_STORAGE_S3_REGIONENDPOINT=${REGISTRY_STORAGE_S3_ENDPOINT}
      - REGISTRY_STORAGE_S3_REGION=${REGISTRY_STORAGE_S3_REGION}
      - REGISTRY_STORAGE_S3_BUCKET=${REGISTRY_STORAGE_S3_BUCKET}
      - REGISTRY_STORAGE_S3_ACCESSKEY=${REGISTRY_STORAGE_S3_ACCESS_KEY}
      - REGISTRY_STORAGE_S3_SECRETKEY=${REGISTRY_STORAGE_S3_SECRET_KEY}
    volumes:
      - registry_config:/etc/docker/registry

  registry:
    image: ${REGISTRY_IMAGE}
    depends_on:
      config:
        condition: service_completed_successfully
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - SETUID
      - SETGID
    security_opt:
      - no-new-privileges:true
    sysctls:
      - net.ipv4.ip_unprivileged_port_start=1024
    restart: unless-stopped
    volumes:
      - registry_config:/etc/docker/registry:ro
    # All labels are defined in the template: docker-compose.instance.yaml
    labels: []
