ARG IMAGE=lscr.io/linuxserver/webtop:alpine-xfce
FROM ${IMAGE}

RUN apk update && \
    apk add --no-cache iproute2 iptables nftables iputils-ping gosu ca-certificates libcap && \
    rm -rf /var/cache/apk/*

COPY app-router-bootstrap.sh /usr/local/bin/app-router-bootstrap.sh
RUN chmod 0555 /usr/local/bin/app-router-bootstrap.sh

ARG PUID=1000
ARG PGID=1000

ENV ENTRYPOINT=/init
ENTRYPOINT ["/usr/local/bin/app-router-bootstrap.sh"]
