server_name: ${NATS_CLUSTER_NAME}
listen: 0.0.0.0:4222
http: 0.0.0.0:8222

tls {
  cert_file: /certs/${NATS_TRAEFIK_HOST}.crt
  key_file: /certs/${NATS_TRAEFIK_HOST}.key
  ca_file: /certs/root_ca.crt
  verify_and_map: true
}
