[Interface]
Address = ${BITMAGNET_VPN_CLIENT_INTERFACE_IPV4},${BITMAGNET_VPN_CLIENT_INTERFACE_IPV6}
PrivateKey = ${BITMAGNET_VPN_CLIENT_INTERFACE_PRIVATE_KEY}
ListenPort = ${BITMAGNET_VPN_CLIENT_INTERFACE_LISTEN_PORT}
DNS = ${BITMAGNET_VPN_CLIENT_INTERFACE_PEER_DNS}

[Peer]
PublicKey = ${BITMAGNET_VPN_CLIENT_PEER_PUBLIC_KEY}
Endpoint = ${BITMAGNET_VPN_CLIENT_PEER_ENDPOINT}
AllowedIPs = ${BITMAGNET_VPN_CLIENT_PEER_ALLOWED_IPS}
