services:
  llama-cpu:
    profiles:
      - cpu
    image: ${LLAMA_IMAGE}:${LLAMA_IMAGE_VARIANT}
    restart: unless-stopped
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    sysctls:
      - net.ipv4.ip_unprivileged_port_start=1024

  llama-cuda:
    profiles:
      - cuda
    image: ${LLAMA_IMAGE}:${LLAMA_IMAGE_VARIANT}-cuda
    restart: unless-stopped
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    sysctls:
      - net.ipv4.ip_unprivileged_port_start=1024
    devices:
      - nvidia.com/gpu=all

  llama-rocm:
    profiles:
      - rocm
    image: ${LLAMA_IMAGE}:${LLAMA_IMAGE_VARIANT}-rocm
    restart: unless-stopped
    devices:
      - /dev/kfd
      - /dev/dri
    security_opt:
      - seccomp=unconfined
      - no-new-privileges:true
    group_add:
      - video
      - render
    cap_drop:
      - ALL
    sysctls:
      - net.ipv4.ip_unprivileged_port_start=1024
    environment:
      - HSA_OVERRIDE_GFX_VERSION=${LLAMA_HSA_OVERRIDE_GFX_VERSION}

volumes:
  llama:
