ROOT_DIR = ..
include ../_scripts/Makefile.projects

# .PHONY: config-hook # Configure .env file
# config-hook:
# 	@${BIN}/reconfigure_ask ${ENV_FILE} GITEA_TRAEFIK_HOST "Enter the gitea domain name (eg. git.example.com)"
