#!/usr/bin/env bash

BIN=$(dirname ${BASH_SOURCE})
source ${BIN}/funcs.sh

missing=""
for var in "$@"; do
    echo -n "Looking for ${var} ... " >/dev/stderr
    if ! which "${var}" >/dev/null 2>&1; then
        stderr "Missing! No ${var} found in PATH." >/dev/stderr
        missing="${missing} ${var}"
    else
        stderr found $(which "${var}")
    fi
done

if [[ -n "${missing}" ]]; then fault "Missing dependencies: ${missing}"; fi

