#!/bin/bash

BIN=$(realpath $(dirname ${BASH_SOURCE}))
source ${BIN}/funcs.sh

## Confirm with the user
## Check env for the var YES, if it equals "yes" then bypass this confirm
test ${YES:-no} == "yes" && exit 0

default=$1; prompt=$2; question=${3:-". Proceed?"}

wizard confirm "$prompt$question" "$default"
