#!/usr/bin/env bash

BIN=$(dirname ${BASH_SOURCE})
source ${BIN}/funcs.sh

## Copy a value from another .env file and put it in the current directory's .env file
ENV_FILE=${1}
VAR=${2}
DEST_VAR=${3:-${VAR}}

check_var ENV_FILE
check_var VAR

if [[ -f ${ENV_FILE} ]]; then
    value=$(${BIN}/dotenv -f ${ENV_FILE} get ${VAR})
else
    echo "WARNING: ${ENV_FILE} does not exist, and so ${DEST_VAR} is set blank"
    value=""
fi

${BIN}/dotenv -f ${ENV_FILE} set ${DEST_VAR}=${value}
echo "Set ${DEST_VAR}=${value}"
