#!/bin/bash

## Runs docker container with the listed environment variables set.
## Pass VARS as the name of an array containing the env var names.
## Pass the rest of the docker run args after that.
## docker_run_with_env VARS {rest of docker run command args}..
docker_env() {
    ## construct the env var args string
    ## First arg is the string to return
    declare -n returned_string=$1; shift;
    ## The rest of the args are the names of the environment vars:
    ## Return a string full of all the docker environment vars and values
    __args=""; for var in "$@"; do
                   test -z ${!var} && echo "$var is not set! Exiting." && exit 1
                   __args="${__args} -e $var=${!var}"
               done
    returned_string="${__args}"
}
## Get the array of vars passed by name:
name=$1[@]; ___vars=("${!name}"); ___vars=${___vars[@]}; shift;
## Construct the env var args string and put into DOCKER_ENV:
docker_env DOCKER_ENV $___vars
## Run Docker with the environment set and the rest of the args sent:
set -x
docker run ${DOCKER_ENV} $*
