#!/bin/bash

set -e

if [[ -z "${instance}" ]]; then
    EXISTING_ENVS=$(ls .env_${DOCKER_CONTEXT}_* 2>/dev/null | sed "s/.env_${DOCKER_CONTEXT}_//" || true)
    if [[ -n "$EXISTING_ENVS" ]]; then
        echo "Existing environments:"
        echo "${EXISTING_ENVS}"
        echo ""
    fi
    read -p "Enter an instance name to create/edit: " instance
fi

test -z "$instance" && echo "Missing required instance name." && exit 1
NEW_ENV_FILE="${ENV_FILE}_${instance}"
test ! -f "${NEW_ENV_FILE}" && make --no-print-directory config INSTANCE="${instance}" ENV_FILE="${NEW_ENV_FILE}" DOCKER_CONTEXT=${DOCKER_CONTEXT}
echo "## Entering sub-shell for instance ${instance}".
echo "## Press Ctrl-D to exit or type \`exit\`."
make --no-print-directory switch INSTANCE="${instance}" ENV_FILE="${NEW_ENV_FILE}" DOCKER_CONTEXT=${DOCKER_CONTEXT}
