#!/bin/bash

BIN=$(dirname ${BASH_SOURCE})
source ${BIN}/funcs.sh
set -e

check_var ENV_FILE ROOT_ENV ROOT_DIR

test -f "${ROOT_ENV}" || make -C ${ROOT_DIR} config

echo
echo "Notice: this is a turbo-charged convenience wrapper for configuring and installing d.rymcg.tech apps. This should work for most apps that follow the 'make config' + 'make install' strategy. However, there are a minority of apps that deviate from this generic path, and have additional steps listed in the project README. For those apps, this tool does not capture those extra steps. So, you should double check the project README to be sure." | fold -w 80 -s | sed 's/ $//g'
echo

readarray -t all_projects < <(get_all_projects)
PROJECT=$(wizard choose "Select a project to install" "${all_projects[@]}")
PROJECT_DIR=${ROOT_DIR}/${PROJECT}

echo
if ${BIN}/confirm yes "Before configuration, would you like to read the ${PROJECT} README (recommended)" "?"; then
    make -C "${PROJECT_DIR}" readme
    echo
    ${BIN}/confirm yes "The README should now open up in your web browser (if it does not, copy the URL from the output above). When you're finished reading, this script will proceed to configure, and then install ${PROJECT}. (Press Ctrl-C to cancel)" ""
    echo
fi

echo "Configuring ${PROJECT} ..."
test -d "${PROJECT_DIR}" || fault "Invalid project directory: ${PROJECT_DIR}"
test -f "${PROJECT_DIR}"/Makefile || fault "Missing Makefile: ${PROJECT_DIR}/Makefile"
echo Project dir: "${PROJECT_DIR}"
make -C "${PROJECT_DIR}" config

if ${BIN}/confirm yes "Configuration is complete. Would you like to install it now" "?"; then
    echo "Installing ${PROJECT} ..."
    make -C "${PROJECT_DIR}" install
    echo "Waiting for ${PROJECT} service healthchecks ..."
    make -C "${PROJECT_DIR}" wait

    echo
    echo "The app is ready:"
    make -C "${PROJECT_DIR}" --no-print-directory get-instance-url
    echo
    echo "## Note: the url listed *might* be incorrect, check the README to be sure."
    echo
    if ${BIN}/confirm yes "Would you like to open the app now" "?"; then
        make -C "${PROJECT_DIR}" --no-print-directory open
    fi
else
    echo "OK. You can install this by running: d.rymcg.tech make ${PROJECT} install"
fi
