.PHONY: install # (re)builds images and (re)starts services (only if changed)
install: build start

.PHONY: uninstall # Remove service containers, leaving the volumes intact
uninstall: down

.PHONY: reinstall # Remove service containers, and re-install (volumes left intact).
reinstall: uninstall install
