.PHONY: install # (re)builds images and (re)starts services (only if changed)
install: build install-hook-pre start
	@make -e --no-print-directory install-hook instance=${INSTANCE}

.PHONY: uninstall # Remove service containers, leaving the volumes intact
uninstall: down

.PHONY: reinstall # Remove service containers, and re-install (volumes left intact).
reinstall: uninstall install

.PHONY: install-hook-pre
install-hook-pre:
	@echo pre-hook
