.PHONY: readme # Open the README.md in your web browser
readme:
	@PROJECT_DIR=$$(realpath $$(pwd) | grep -Po "$$(realpath ${ROOT_DIR})\K.*"); URL="https://github.com/EnigmaCurry/d.rymcg.tech/tree/master$${PROJECT_DIR}#readme"; OPENER=$$(${BIN}/d.rymcg.tech info README_OPENER); set -x; $${OPENER} "$${URL}"
