.PHONY: override # Create docker-compose.override_${DOCKER_CONTEXT}_${INSTANCE}.yaml
override:
	@make --no-print-directory override-hook-rule-exists 2>/dev/null && make --no-print-directory override-hook || true
