.PHONY: ps # Show containers status (docker compose ps)
ps:
	@echo "Showing containers for a single instance (use \`make status\` to see all instances.)"
	@make --no-print-directory docker-compose-lifecycle-cmd EXTRA_ARGS="ps -a"
