.PHONY: override # Create docker-compose.override_${DOCKER_CONTEXT}_${INSTANCE}.yaml
override:
	@if make --no-print-directory override-hook-rule-exists 2>/dev/null; then make --no-print-directory override-hook; fi
