.PHONY: instance # Create a duplicate instance with a copy of the current .env file
instance:
	@DOCKER_CONTEXT=${DOCKER_CONTEXT} ENV_FILE=${ENV_FILE} ${BIN}/instance

.PHONY: switch # Switch the default instance and enter a new subshell
switch:
	@(export instance="${instance}"; test -z "$${instance}" && read -p "Enter the temporary default instance name: " instance; bash --rcfile <(echo "export TERM=$$TERM; PATH=$$PATH; export INSTANCE=$${instance}; export PROJECT_INSTANCE=$$(basename $${PWD})_$${instance}; export PROJECT=$$(basename $$PWD); unset MAKELEVEL; PS1='\n(project=$$(basename $$PWD) instance=$${instance})\n\W $$ '") -i)
