#!/bin/bash

## reconfigure_dashboard ENV_FILE

BIN=$(dirname ${BASH_SOURCE})
source ${BIN}/funcs.sh
set -e

ENV_FILE=../traefik/${1}
shift
## Make new .env if it doesn't exist:
test -f ${ENV_FILE} || cp ../traefik/.env-dist ${ENV_FILE}

echo ""
if ${BIN}/confirm $([[ $(${BIN}/dotenv -f ${ENV_FILE} get TRAEFIK_DASHBOARD) == "true" ]] && echo yes || echo no) "Do you want to enable the Traefik dashboard" "?"; then
    ${BIN}/reconfigure ${ENV_FILE} TRAEFIK_DASHBOARD=true
    echo "It's important to protect the dashboard and so a username/password is required."
	${BIN}/reconfigure_htpasswd ${ENV_FILE} TRAEFIK_DASHBOARD_AUTH
else
    ${BIN}/reconfigure ${ENV_FILE} TRAEFIK_DASHBOARD=false
fi
