#!/bin/bash

## reconfigure_ask ENV_FILE VAR "this is the prompt" "this is the default"
## Ask interactive questions to edit/create your .env file
## This ONLY edits the lines with the given variable names in them.

env="$1"; var="$2"; prompt="$3"; default="$4";

BIN=$(dirname ${BASH_SOURCE})
source ${BIN}/funcs.sh

check_var env var prompt

## Make new .env if it doesn't exist:
test -f ${env} || cp .env-dist ${env}

example=$(grep -m 1 -oP "^$var=\K.*" .env-dist)
existing=$(grep -m 1 -oP "^$var=\K.*" ${env})
if [[ $existing != $example ]]; then
    default=${existing:-${default}}
fi

while true; do
    read -e -p "${var}: ${prompt} (eg. ${example}): " -i "${default}" answer
    if [[ -n ${answer} ]] || [[ -z ${default} ]]; then
        break
    fi
done
${BIN}/dotenv -f ${env} set ${var}="${answer}"
