#!/usr/bin/env bash

### Create a new random password, but only if its not set already.
## reconfigure_password ENV_FILE VAR [LENGTH]

BIN=$(dirname ${BASH_SOURCE})
source ${BIN}/funcs.sh
set -e

ENV_FILE="${1}"
PASSWORD_VAR="${2}"
LENGTH="${3:-35}"
check_var ENV_FILE PASSWORD_VAR
check_num LENGTH

if ! [[ -f "${ENV_FILE}" ]]; then
    fault "Environment file not found: ${ENV_FILE}"
fi


if [[ -z "$(${BIN}/dotenv -f ${ENV_FILE} get ${PASSWORD_VAR})" ]]; then
    PASSWORD="$(gen_password ${LENGTH})"
    ${BIN}/reconfigure ${ENV_FILE} ${PASSWORD_VAR}="${PASSWORD}"
else
    echo "# Using existing password for ${PASSWORD_VAR}"
fi
