#!/bin/bash

## reconfigure_auth ENV_FILE VAR_PREFIX [CUSTOM_PROMPT] [ALLOWED_METHODS]
## Subsume all the authentication and authorization configurations in 1 script
## CUSTOM_PROMPT: optional custom prompt string (default: generic sentry auth prompt)
## ALLOWED_METHODS: optional comma-separated whitelist of auth methods (http,oauth,mtls)
##   If omitted, all methods supported by the .env file are available.

BIN=$(dirname ${BASH_SOURCE})
source ${BIN}/funcs.sh
set -eo pipefail

ENV_FILE=$1
VAR_PREFIX=$2
CUSTOM_PROMPT=$3
ALLOWED_METHODS=$4
export __D_RY_CONFIG_ENTRY=reconfigure_auth

prompt="${CUSTOM_PROMPT:-Do you want to enable sentry authorization in front of this app (effectively making the entire site private)?}"
options=("No")
## Set default based on current auth settings in ENV_FILE

DISABLE_HTTP=false
DISABLE_OAUTH=false
DISABLE_MTLS=false

## If an allowed methods whitelist is given, disable everything not listed
if [[ -n "${ALLOWED_METHODS}" ]]; then
    DISABLE_HTTP=true
    DISABLE_OAUTH=true
    DISABLE_MTLS=true
    IFS=',' read -ra methods <<< "${ALLOWED_METHODS}"
    for method in "${methods[@]}"; do
        case "${method}" in
            http) DISABLE_HTTP=false ;;
            oauth) DISABLE_OAUTH=false ;;
            mtls) DISABLE_MTLS=false ;;
        esac
    done
fi

set +e
http_auth=$(${BIN}/dotenv -f ${ENV_FILE} get ${VAR_PREFIX}_HTTP_AUTH)
if [[ "$?" != "0" ]]; then DISABLE_HTTP=true; http_auth="";  fi
oauth2_auth=$(${BIN}/dotenv -f ${ENV_FILE} get ${VAR_PREFIX}_OAUTH2)
if [[ "$?" != "0" ]]; then DISABLE_OAUTH=true; oauth2_auth=""; fi
mtls_auth=$(${BIN}/dotenv -f ${ENV_FILE} get ${VAR_PREFIX}_MTLS_AUTH)
if [[ "$?" != "0" ]]; then DISABLE_MTLS=true; mtls_auth=false; fi
set -e

unset_oauth2() {
    if [[ "${DISABLE_OAUTH}" == "false" ]]; then
        ${BIN}/reconfigure ${ENV_FILE} "${VAR_PREFIX}_OAUTH2"=
    fi
}
unset_http_auth() {
    if [[ "${DISABLE_HTTP}" == "false" ]]; then
        ${BIN}/reconfigure ${ENV_FILE} "${VAR_PREFIX}_HTTP_AUTH"=
        TMP_PASSWORD=$(mktemp)
        if [[ -f passwords.json ]]; then
            cat passwords.json | jq "del(.\"${CONTEXT_INSTANCE}\")" > ${TMP_PASSWORD} && mv ${TMP_PASSWORD} passwords.json
        fi
    fi
}
unset_mtls_auth() {
    if [[ "${DISABLE_MTLS}" == "false" ]]; then
        ${BIN}/reconfigure ${ENV_FILE} "${VAR_PREFIX}_MTLS_AUTH"=false
    fi
}


if [[ "${DISABLE_HTTP}" == "false" ]]; then
    options+=("Yes, with HTTP Basic Authentication")
fi
if [[ "${DISABLE_OAUTH}" == "false" ]]; then
    options+=("Yes, with Oauth2")
fi
if [[ "${DISABLE_MTLS}" == "false" ]]; then
    options+=("Yes, with Mutual TLS (mTLS)")
fi

default="${options[0]}"
if [[ -n "${http_auth}" ]]; then
    for opt in "${options[@]}"; do [[ "$opt" == *HTTP* ]] && default="$opt" && break; done
elif [[ "${oauth2_auth}" == "true" ]]; then
    for opt in "${options[@]}"; do [[ "$opt" == *Oauth2* ]] && default="$opt" && break; done
elif [[ "${mtls_auth}" == "true" ]]; then
    for opt in "${options[@]}"; do [[ "$opt" == *mTLS* ]] && default="$opt" && break; done
fi

## Ask user which authentication configuration they want
choice=$(eval "${BIN}/script-wizard choose ${prompt@Q} ${options[@]@Q} --default ${default@Q}")

## Configure authentication per user's choice
case "${choice}" in
    No)
        unset_oauth2
        unset_http_auth
        unset_mtls_auth
        ;;
    *HTTP*)
        ${BIN}/reconfigure_htpasswd ${ENV_FILE} ${VAR_PREFIX}_HTTP_AUTH default=no && unset_oauth2 && unset_mtls_auth
        ;;
    *Oauth2*)
        ${BIN}/reconfigure_oauth2 ${ENV_FILE} ${VAR_PREFIX} && unset_http_auth && unset_mtls_auth
        ;;
    *mTLS*)
        ${BIN}/reconfigure_mtls ${ENV_FILE} ${VAR_PREFIX} && unset_http_auth && unset_oauth2
        ;;
    *)
        echo "Unknown option."
        exit 1
esac
