#!/bin/bash

## reconfigure_ask VAR "this is the prompt" "this is the default"
## Ask interactive questions to edit/create your .env file
## This ONLY edits the lines with the given variable names in them.

var=$1; prompt=$2; default=$3;

BIN=$(dirname ${BASH_SOURCE})
env=${ENV_FILE:-.env}
env_dist=${ENV_DIST_FILE:-.env-dist}

## Make new .env if it doesn't exist:
test -f ${env} || cp ${env_dist} ${env}

example=$(grep -m 1 -oP "^$var=\K.*" ${env_dist})
existing=$(grep -m 1 -oP "^$var=\K.*" ${env})
if [[ $existing != $example ]]; then
    default=${existing:-${default}}
fi

while true; do
    read -e -p "${var}: ${prompt} (eg. ${example}): " -i "${default}" answer
    if [[ -n ${answer} ]] || [[ -z ${default} ]]; then
        break
    fi
done
${BIN}/dotenv -f ${env} set ${var}="${answer}"
