#!/bin/bash

## reconfigure_ask ENV_FILE VAR "this is the prompt" "this is the default"
## Ask interactive questions to edit/create your .env file
## This ONLY edits the lines with the given variable names in them.

ENV_FILE="$1"; var="$2"; prompt="$3"; default="$4";

BIN=$(dirname ${BASH_SOURCE})
source ${BIN}/funcs.sh

check_var ENV_FILE var prompt

## Make new .env if it doesn't exist:
test -f ${ENV_FILE} || cp .env-dist ${ENV_FILE}

example=$(grep -m 1 -oP "^$var=\K.*" .env-dist)
existing=$(grep -m 1 -oP "^$var=\K.*" ${ENV_FILE})
if [[ $existing != $example ]]; then
    default=${existing:-${default}}
else
    default=${example}
fi

if [[ -n "${example}" ]]; then
    example="(eg. ${example})"
fi
while true; do
    read -e -p "${var}: ${prompt} ${example}"$'\x0a: ' -i "${default}" answer
    if [[ -n ${answer} || -z ${default} || "${ALLOW_BLANK}" == 1 ]]; then
        break
    fi
done
${BIN}/dotenv -f ${ENV_FILE} set ${var}="${answer}"
