#!/bin/bash

## reconfigure_ask_host_port ENV_FILE VAR "this is the prompt" "this is the default"
## Validate input to be a hostname:port tuple

ENV_FILE="$1"; var="$2"; prompt="$3"; default="$4";

BIN=$(dirname ${BASH_SOURCE})
source ${BIN}/funcs.sh

${BIN}/reconfigure_ask_validate_regex ${ENV_FILE} ${var} "${prompt}" "${default}" "^[_\+\-\.a-zA-Z0-9]+@[\-\.a-zA-Z0-9]+$"
