#!/usr/bin/env bash

## reconfigure_editor ENV_FILE VAR PROMPT
## Allows user to edit a variable in the .env file using a full text editor

## Example:
## ${BIN}/reconfigure_editor .env BIOGRAPHY "Tell me about yourself"

ENV_FILE="$1"; shift
var="$1"; shift
prompt="$1"; shift

BIN=$(dirname ${BASH_SOURCE})
source ${BIN}/funcs.sh

check_var ENV_FILE var prompt
set -e

## Make new .env if it doesn't exist:
test -f ${ENV_FILE} || cp .env-dist ${ENV_FILE}
replace_newlines() {
    sed ':a;N;$!ba;s/\n/\\n/g'; return 0;
}
strip_outer_quotes() {
    sed 's/^"\(.*\)"$/\1/'; return 0;
}

eval $(${BIN}/dotenv -f "${ENV_FILE}" export "${var}" | strip_outer_quotes)
DEFAULT=${!var}
debug_var DEFAULT

answer=$(launch_editor_for_response "${prompt}" "${DEFAULT}" | strip_outer_quotes | replace_newlines)

## Set the final answer:
${BIN}/reconfigure ${ENV_FILE} ${var}="${answer}"
