#!/bin/bash

BIN=$(dirname ${BASH_SOURCE})

ENV_FILE=$1; shift

## Edit/create the .env file setting the vars given as args.
test -f ${ENV_FILE} || cp .env-dist ${ENV_FILE}
for var in "$@"; do
    parts=(${var//=/ }); var=${parts[0]}; val=${parts[@]:1};
    ${BIN}/dotenv -f ${ENV_FILE} set ${var}="${val}"
    echo "Set ${var}=${val}"
done
