#!/bin/bash

## reconfigure_htpasswd VAR "Enter username for thing"

BIN=$(dirname ${BASH_SOURCE})
env=${ENV_FILE:-.env}
env_dist=${ENV_DIST_FILE:-.env-dist}

var=$1;
## Make new .env if it doesn't exist:
test -f ${env} || cp ${env-dist} ${env}

docker build -t localhost/traefik-htpasswd ../traefik-htpasswd && docker run --rm -it localhost/traefik-htpasswd

read -p "${var}: Copy and paste the 'Hashed username/password' printed above: " hashed_password
${BIN}/dotenv -f ${env} set ${var}="${hashed_password}"

