#!/bin/bash

### Create a new random password, but only if its not set already.
## reconfigure_password ENV_FILE VAR

BIN=$(dirname ${BASH_SOURCE})
source ${BIN}/funcs.sh
set -e

ENV_FILE="${1}"
PASSWORD_VAR="${2}"
check_var ENV_FILE PASSWORD_VAR
if ! [[ -f "${ENV_FILE}" ]]; then
    fault "Environment file not found: ${ENV_FILE}"
fi

if [[ -z "$(${BIN}/dotenv -f ${ENV_FILE} get ${PASSWORD_VAR})" ]]; then
    ${BIN}/reconfigure ${ENV_FILE} ${PASSWORD_VAR}=$(openssl rand -base64 35 | tr '=' '0' | tr '+' '0' | tr '/' '0')
else
    echo "# Using existing password for ${PASSWORD_VAR}"
fi
