#!/bin/bash

## reconfigure_htpasswd VAR "Enter username for thing"

var=$1; 
## Make new .env if it doesn't exist:
test -f .env || cp .env-dist .env

docker build -t localhost/traefik-htpasswd ../traefik-htpasswd && docker run --rm -it localhost/traefik-htpasswd

read -p "${var}: Copy and paste the 'Hashed username/password' printed above: " hashed_password
escaped_password=$(printf '%s\n' "${hashed_password}" | sed -e 's/[\/&]/\\&/g')
sed -i "s/^${var}=.*/${var}='${escaped_password}'/" .env

