#!/usr/bin/env bash

BIN=$(dirname ${BASH_SOURCE})
source ${BIN}/funcs.sh
[[ $# < 1 ]] && fault "# help: tls_debug domain [port]"

DESTINATION=${1}
PORT=${2:-443}

set -x
openssl s_client -connect "$DESTINATION:$PORT" </dev/null
