#!/bin/bash
set -Eeo pipefail

# shellcheck disable=2154
# trap 's=$?; echo "$0: Error on line "$LINENO": $BASH_COMMAND"; exit $s' ERR

# Extended regular expression (ERE) for arguments
reUser='[A-Za-z0-9._][A-Za-z0-9._-]{0,31}' # POSIX.1-2008
reProvider="(gh|lp|github|launchpad|url)"
reUsername='[^:]{0,255}'
reUid='[[:digit:]]*'
reGid='[[:digit:]]*'
reDir='[^:]*'
#reArgs="^($reUser)(:$reProvider)(:$reUsername)(:$reUid)?(:$reGid)?(:$reDir)?$"

function log() {
    echo "[$0] $*"
}

function validateArg() {
    name="$1"
    val="$2"
    re="$3"

    if [[ "$val" =~ ^$re$ ]]; then
        return 0
    else
        log "ERROR: Invalid $name \"$val\", do not match required regex pattern: $re"
        return 1
    fi
}

log "Parsing user data: \"$1\""
IFS=':' read -ra args <<< "$1"

skipIndex=0
chpasswdOptions=""
useraddOptions=(--no-user-group)

user="${args[0]}"; validateArg "username" "$user" "$reUser" || exit 1
provider="${args[1]}"; validateArg "provider" "$provider" "$reProvider" || exit 1
provider_prefix=""
username="${args[2]}"; validateArg "username" "$username" "$reUsername" || exit 1
log "User: $user"

log "Key Provider: $provider"
if [ $provider = "url" ] && [ -v KEYFILE_URL ]; then log "Keyfile URL: ${KEYFILE_URL}"; fi
log "Provider Username: $username"

uid="${args[$((skipIndex+3))]}"; validateArg "UID" "$uid" "$reUid" || exit 1
gid="${args[$((skipIndex+4))]}"; validateArg "GID" "$gid" "$reGid" || exit 1
dir="${args[$((skipIndex+5))]}"; validateArg "dirs" "$dir" "$reDir" || exit 1
log "UID: $uid"
log "GID: $gid"
log "directories: $dir"

if getent passwd "$user" > /dev/null; then
    log "WARNING: User \"$user\" already exists. Skipping."
    exit 0
fi

if [ -n "$uid" ]; then
    useraddOptions+=(--non-unique --uid "$uid")
fi

if [ -n "$gid" ]; then
    if ! getent group "$gid" > /dev/null; then
        groupadd --gid "$gid" "group_$gid"
    fi

    useraddOptions+=(--gid "$gid")
fi

useradd "${useraddOptions[@]}" "$user"
mkdir -p "/home/$user"
chown root:root "/home/$user"
chmod 755 "/home/$user"

# Retrieving user id to use it in chown commands instead of the user name
# to avoid problems on alpine when the user name contains a '.'
uid="$(id -u "$user")"

usermod -p "*" "$user" # disabled password

# Make sure dirs exists
if [ -n "$dir" ]; then
    IFS=',' read -ra dirArgs <<< "$dir"
    for dirPath in "${dirArgs[@]}"; do
        dirPath="/home/$user/$dirPath"
        if [ ! -d "$dirPath" ]; then
            log "Creating directory: $dirPath"
            mkdir -p "$dirPath"
            chown -R "$uid:users" "$dirPath"
        else
            log "Directory already exists: $dirPath"
        fi
    done
fi

## Import authorized_keys from a key provider via ssh-import-id
if [ "$provider" = "github" ] || [ "$provider" = "gh" ]; then
    (set -x; ssh-import-id -o /etc/ssh/keys/"${user}"_authorized_keys gh:"${username}")
elif [ "$provider" = "launchpad" ] || [ "$provider" = "lp" ]; then
    (set -x; ssh-import-id -o /etc/ssh/keys/"${user}"_authorized_keys lp:"${username}")
elif [ "$provider" = "url" ]; then
    (set -x; URL="${KEYFILE_URL}" ssh-import-id -o /etc/ssh/keys/"${user}"_authorized_keys "${username}")
fi
chown $user:root /etc/ssh/keys/${user}_authorized_keys
