version: '3'

networks:
  traefik-proxy:
    name: traefik-proxy

volumes:
  etcd:
  pgsql:
  config:
  
services:
  etcd:
    image: quay.io/coreos/etcd:v3.4.16
    volumes:
      - etcd:/etcd_data
    command:
      - /usr/local/bin/etcd
      - -name
      - etcd
      - --data-dir
      - /etcd_data
      - -advertise-client-urls
      - http://etcd:2379
      - -listen-client-urls
      - http://0.0.0.0:2379
      - -initial-advertise-peer-urls
      - http://etcd:2380
      - -listen-peer-urls
      - http://0.0.0.0:2380

  pgsql:
    build:
      context: pgsql
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    volumes:
      - pgsql:/var/lib/postgresql/data

  jackal-config:
    build:
      context: jackal-config
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - JACKAL_HOST
      - PRINT_CONFIG
      - SELF_SIGNED_TLS
    volumes:
      - config:/config

  jackal:
    depends_on:
      - jackal-config
    build:
      context: jackal
    ### Ports are not exposed directly, but through Traefik instead:
    # ports:
    #   - 5222:5222
    #   - 5223:5223
    #   - 5269:5269
    #   - 5270:5270
    #   - 127.0.0.1:15280:15280
    networks:
      - default
      - traefik-proxy
    volumes:
      - config:/config
    environment:
      - JACKAL_LOG_STANZAS=on
      - JACKAL_CONFIG_FILE=/config/config.yaml
    depends_on:
      - etcd
      - pgsql
    labels:
      - "traefik.enable=true"
      ## Jabber client to server (C2S)
      - "traefik.tcp.routers.xmpp_c2s.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.xmpp_c2s.entrypoints=xmpp_c2s"
      - "traefik.tcp.routers.xmpp_c2s.service=xmpp_c2s"
      - "traefik.tcp.services.xmpp_c2s.loadbalancer.server.port=5222"
      - "traefik.tcp.middlewares.xmpp_c2s-ipwhitelist.ipwhitelist.sourcerange=${C2S_SOURCERANGE}"
      - "traefik.tcp.routers.xmpp_c2s.middlewares=xmpp_c2s-ipwhitelist@docker"
      ## Jabber server to server (S2S)
      - "traefik.tcp.routers.xmpp_s2s.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.xmpp_s2s.entrypoints=xmpp_s2s"
      - "traefik.tcp.routers.xmpp_s2s.service=xmpp_s2s"
      - "traefik.tcp.services.xmpp_s2s.loadbalancer.server.port=5269"
      - "traefik.tcp.middlewares.xmpp_s2s-ipwhitelist.ipwhitelist.sourcerange=${S2S_SOURCERANGE}"
      - "traefik.tcp.routers.xmpp_s2s.middlewares=xmpp_s2s-ipwhitelist@docker"

