version: '3'

volumes:
  etcd:
    
networks:
  traefik-proxy:
    external:
      name: traefik-proxy
  jackal:

services:
  etcd:
    image: quay.io/coreos/etcd:v3.4.16
    container_name: jackal-etcd
    restart: unless-stopped
    networks:
      - jackal
    volumes:
      - etcd:/etcd_data
    command:
      - /usr/local/bin/etcd
      - -name
      - etcd
      - --data-dir
      - /etcd_data
      - -advertise-client-urls
      - http://etcd:2379
      - -listen-client-urls
      - http://0.0.0.0:2379
      - -initial-advertise-peer-urls
      - http://etcd:2380
      - -listen-peer-urls
      - http://0.0.0.0:2380

  pgsql:
    networks:
      - jackal
    build: 
      context: ./postgres
    container_name: jackal-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
#    volumes:
#      - ../sql/postgres.up.psql:/docker-entrypoint-initdb.d/01-schema.sql

  jackal:
    build:
      context: ./jackal
    container_name: jackal
    restart: unless-stopped
    ports:
      - 5222:5222
      - 15280:15280
    environment:
      - JACKAL_LOG_STANZAS=on
    depends_on:
      - etcd
      - pgsql
    working_dir: /jackal
#    volumes:
#      - ../scripts/wait-for-it.sh:/jackal/wait-for-it.sh
#      - ../config/docker-compose.config.yaml:/jackal/config.yaml
    command:
      - ./wait-for-it.sh
      - pgsql:5432
      - --
      - ./wait-for-it.sh
      - etcd:2379
      - --
      - ./jackal
    networks:
      - traefik-proxy
      - jackal
    labels:
      - "traefik.enable=true"
      ## Web
      - "traefik.http.routers.jackal.rule=Host(`${JACKAL_TRAEFIK_HOST}`)"
      - "traefik.http.routers.jackal.entrypoints=websecure"
      - "traefik.http.routers.jackal.tls.certresolver=${ACME_CERT_RESOLVER}"
